replicaCount: 1

image:
  repository: ggur/project
  pullPolicy: IfNotPresent

  tag: "NOT PUBLIC"

imagePullSecrets:
  - name: ""
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  
  create: true
  
  annotations: {}
  
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "false"
    haproxy.org/cors-enable: "true"
  hosts:
    - host: your domain info
      paths:
        - path: /
          pathType: Prefix

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
