- hosts: Routers 
  gather_facts: no
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_network_os: ios
    ansible_user: username
    ansible_ssh_pass: password
  
  tasks:
    - name: Gather facts (ops)
      ios_facts:
        gather_subset: all
        gather_network_resources: all
      when: ansible_network_os == 'ios'

- hosts: localhost
  gather_facts: false

  tasks:
    - name: set fact another groups information
      set_fact: 
        information: "{{ hostvars[groups['Routers'][0]]}}"  
          
    - name: Create vlan within Netbox with only required information
      netbox.netbox.netbox_vlan:
        netbox_url: https를 포함한 netbox url 경로
        netbox_token: 차트 value 에서 정의한 token (google API 키를 등록하여 사용)
        data:
          site: TEST # 미리 정의된 값
          name: "{{item.name}}" 
          vid: "{{item.vlan_id}}"
        state: present
      with_items: "{{information.ansible_facts.network_resources.vlans}}"
